version: "3.7"

volumes: 
  customers_db_data:
  products_db_data:
  rabbitmq_data:

services:
  # queue:
  #   container_name: queue
  #   image: rabbitmq:3.8-rc-management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   environment: 
  #     - RABBITMQ_DEFAULT_USER=$USER
  #     - RABBITMQ_DEFAULT_PASS=$USER
  #   volumes: 
  #     - type: volume
  #       source: rabbitmq_data
  #       target: /var/lib/rabbitmq
  #   restart: on-failure
  customers:
    container_name: customers
    image: msimou/customers:distributed-transactions
    build:
      context: ./services/customers
      dockerfile: ./deployments/dockerfile
      args:
        - DB_URI=postgresql://$USER:$USER@customers_db:5432/customers?sslmode=disable
    ports:
      - 3000:3000
    environment: 
      - PORT=3000
      - DB_URI=postgresql://$USER:$USER@customers_db:5432/customers?sslmode=disable
    volumes: 
      - type: bind
        source: $PWD/services/customers
        target: /go/src/app
    depends_on: 
      - customers_db
      # - queue
    restart: on-failure
  customers_db:
    container_name: customers_db
    image: postgres:12
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=$USER
      - POSTGRES_USER=$USER
      - POSTGRES_DB=customers
    volumes:
      - type: volume
        source: customers_db_data
        target: /var/lib/postgresql/data
    restart: on-failure
  # products:
  #   container_name: products
  #   image: msimou/products:distributed-transactions
  #   build:
  #     context: ./services/products
  #     dockerfile: ./deployments/dockerfile
  #   ports:
  #     - 4000:4000
  #   environment: 
  #     - PORT=4000
  #   volumes: 
  #     - type: bind
  #       source: $PWD/services/products
  #       target: /go/src/app
  #   depends_on: 
  #     - products_db
  #     - queue
  #   restart: on-failure
  # products_db:
  #   container_name: products_db
  #   image: postgres:12
  #   ports:
  #     - 5433:5432
  #   environment: 
  #     - POSTGRES_PASSWORD=$USER
  #     - POSTGRES_USER=$USER
  #     - POSTGRES_DB=products
  #   volumes:
  #     - type: volume
  #       source: products_db_data
  #       target: /var/lib/postgresql/data
  #   restart: on-failure