//
// Code generated by go-jet DO NOT EDIT.
// Generated at Sunday, 03-May-20 10:27:11 UTC
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Sessions struct {
	ID        int32 `sql:"primary_key"`
	UserID    int32
	GUID      string
	CreatedAt time.Time
	ExpiresAt time.Time
}
