//
// Code generated by go-jet DO NOT EDIT.
// Generated at Friday, 01-May-20 21:26:47 UTC
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Sessions struct {
	ID        int32 `sql:"primary_key"`
	UserID    int32
	GUID      string
	CreatedAt *time.Time
	ExpiresAt time.Time
}
