//
// Code generated by go-jet DO NOT EDIT.
// Generated at Thursday, 23-Apr-20 17:38:27 UTC
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Users struct {
	ID        int32 `sql:"primary_key"`
	Username  string
	Email     string
	Password  string
	Balance   *float64
	CreatedAt *time.Time
	UpdatedAt *time.Time
}
