// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	rabbitmq "customers/internal/rabbitmq"

	mock "github.com/stretchr/testify/mock"
)

// ConnectionInterface is an autogenerated mock type for the ConnectionInterface type
type ConnectionInterface struct {
	mock.Mock
}

// Channel provides a mock function with given fields: _a0
func (_m *ConnectionInterface) Channel(_a0 string) (rabbitmq.ChannelInterface, error) {
	ret := _m.Called(_a0)

	var r0 rabbitmq.ChannelInterface
	if rf, ok := ret.Get(0).(func(string) rabbitmq.ChannelInterface); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rabbitmq.ChannelInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Close provides a mock function with given fields:
func (_m *ConnectionInterface) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
