//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 05-May-20 21:51:13 UTC
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Orders struct {
	ID        int32 `json:"id" sql:"primary_key"`
	UID       string `json:"uid"`
	ProductID int32 `json:"productId"`
	Quantity  int32 `json:"quantity"`
	Total     float64 `json:"total"`
	UserID    int32 `json:"userId"`
	Status    *OrderStatus `json:"status"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
