//
// Code generated by go-jet DO NOT EDIT.
// Generated at Saturday, 25-Apr-20 15:08:35 UTC
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type OrderStatus string

const (
	OrderStatus_Pending  OrderStatus = "pending"
	OrderStatus_Accepted OrderStatus = "accepted"
	OrderStatus_Declined OrderStatus = "declined"
)

func (e *OrderStatus) Scan(value interface{}) error {
	if v, ok := value.(string); !ok {
		return errors.New("jet: Invalid data for OrderStatus enum")
	} else {
		switch string(v) {
		case "pending":
			*e = OrderStatus_Pending
		case "accepted":
			*e = OrderStatus_Accepted
		case "declined":
			*e = OrderStatus_Declined
		default:
			return errors.New("jet: Inavlid data " + string(v) + "for OrderStatus enum")
		}

		return nil
	}
}

func (e OrderStatus) String() string {
	return string(e)
}
