//
// Code generated by go-jet DO NOT EDIT.
// Generated at Sunday, 03-May-20 17:43:30 UTC
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Products struct {
	ID          int32 `sql:"primary_key"`
	Name        string
	Description string
	Price       float64
	Quantity    *int32
	Currency    *Currency
	Image       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
