//
// Code generated by go-jet DO NOT EDIT.
// Generated at Sunday, 03-May-20 12:39:38 UTC
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type SchemaMigrations struct {
	Version int64 `sql:"primary_key"`
	Dirty   bool
}
